dependencies:
- name: zookeeper
  version: 0.1.1
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
- name: postgresql
  version: 0.2.0
  repository: http://storage.googleapis.com/kubernetes-charts