# Default values for druid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

#TODO remove quickstart stuff
iapVersion: "imply-1.3.1"
debug: "True"

postgresqlName: "postgresql"
zkName: "druid-zk"

zookeeper:
  Replicas: 1
  Name: druid-zk
postgresql:
  postgresUser: druid
  postgresDatabase: druid
  postgresPassword: secret

nodes:
  coordinator:
    name: "coordinator"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-coordinator
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-coordinator-service
      type: NodePort
      ports:
        - name: coordinator-port
          port: 8081
  historical:
    name: "historical"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-historical
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-historical-service
      type: ClusterIP
      ports:
        - name: historical-port
          port: 8083
  broker:
    name: "broker"
    replicaCount: 1
    image:
      repository: jkaralus/druid8s-broker
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: druid-broker-service
      type: NodePort
      ports:
        - name: broker-port
          port: 8082


image:
  historical:
    repository: jkaralus/druid8s-historical
    tag: latest
    pullPolicy: IfNotPresent
  quickstart:
    repository: jkaralus/druid8s-quickstart
    tag: latest
    pullPolicy: IfNotPresent
service:
  historical:
    name: historical
    type: ClusterIP
    externalPort: 8083
    internalPort: 8083
  quickstart:
    name: quickstart
    type: NodePort
    port: 9095
  #TODO remove ulgy hotfix
  type: NodePort





resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

