apiVersion: v1
kind: Pod
metadata:
  name: druid-local-zk-pod
  labels:
    name: druid-local-zk-pod
    context: druid-k8s
spec:
  containers:
    -
      name: druid-local-zk
      image: jkaralus/druid8s-local-zk:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: druid-local-zk-service
  labels:
    name: druid-local-zk-pod
    context: druid-k8s
spec:
  type: NodePort
   ports:
     - name: client
       port: 2181
     - name: follower
       port: 2888
     - name: election
       port: 3888
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: druid-local-zk-pod
    context: druid-k8s
