apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodes.broker.service.name }}
  #TODO flexible service Name, configMap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nodes.broker.service.type }}
  ports:
  {{range .Values.nodes.broker.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{end}}
  selector:
    name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-rc"