apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.nodes.broker.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-rc"
        app: {{ template "fullname" . }}
    spec:
      hostname: broker
      subdomain: druid
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}"
        image: "{{ .Values.nodes.broker.image.repository }}:{{ .Values.nodes.broker.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.broker.image.pullPolicy }}
        volumeMounts:
          - name: config-volume
            mountPath: "/iap-druid/{{ .Values.iapVersion }}/conf/druid/_common/"

        #TODO add readiness & liveness probes
        #TODO reenable ressources here
        ports:
        {{range .Values.nodes.broker.service.ports }}
          - containerPort: {{ .port }}
        {{end}}

      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: common.runtime.properties
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodes.broker.service.name }}
  #TODO flexible service Name, configMap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nodes.broker.service.type }}
  ports:
  {{range .Values.nodes.broker.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{end}}
  selector:
    name: "{{ .Chart.Name }}-{{ .Values.nodes.broker.name }}-rc"