apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.nodes.historical.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-rc"
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}"
        image: "{{ .Values.nodes.historical.image.repository }}:{{ .Values.nodes.historical.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.historical.image.pullPolicy }}
        ports:
        {{range .Values.nodes.historical.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        #TODO add readiness & liveness probes
        volumeMounts:
          - name: data
            mountPath: /var/druid/segments
          - name: config-volume
            mountPath: "/iap-druid/{{ .Values.iapVersion }}/conf/druid/_common/"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.druidSegmentDeepStorage }}
      - name: config-volume
        configMap:
          name: common-runtime-configmap
          items:
          - key: common.runtime.properties
            path: common.runtime.properties
