apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodes.historical.service.name }}
  #TODO flexible service Name, configMap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nodes.historical.service.type }}
  ports:
  {{range .Values.nodes.historical.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{end}}
  selector:
    name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-rc"