apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.nodes.middlemanager.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}-rc"
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}"
        image: "{{ .Values.nodes.middlemanager.image.repository }}:{{ .Values.nodes.middlemanager.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.middlemanager.image.pullPolicy }}
        ports:
        {{range .Values.nodes.middlemanager.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        volumeMounts:
        - name: config-volume
          mountPath: "/iap-druid/{{ .Values.iapVersion }}/conf/druid/"
        #TODO add readiness & liveness probes
      volumes:
        - name: config-volume
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: "{{ .Values.nodes.middlemanager.name }}.runtime.properties"
              path: middleManager/runtime.properties
            - key: "{{ .Values.nodes.middlemanager.name }}.jvm.config"
              path: middleManager/jvm.config
            - key: "{{ .Values.nodes.middlemanager.name }}.main.config"
              path: middleManager/main.config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodes.middlemanager.service.name }}
  #TODO flexible service Name, configMap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nodes.middlemanager.service.type }}
  ports:
  {{range .Values.nodes.middlemanager.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{end}}
  selector:
    name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}-rc"